### ISSUE TITLE
Le site de météo a changé

### ISSUE THREAD

**Issue by Aymkdn** [JpEncausse/SARAH-Plugin-Meteo#1]
Le site a complètement été revu, donc le plugin ne marche pas.

Le bon point c'est que le site utilise maintenant du JSON ! Donc il suffit d'avoir la bonne URL et de la parser.

Par contre, il n'est pas simple de trouver l'URL pour sa ville. Par exemple pour Montpellier (34000) ça sera : http://www.meteo-france.mobi/ws/getDetail/france/342020.json

On a donc le numéro de département en premier ("34") puis un nombre avec quatre chiffres qui représente la ville. Je n'ai pas trop eu le temps de chercher comment retrouver cette info facilement. Pour Montpellier je l'ai trouvé en regardant les requêtes avec Firebug...

Une fois qu'on a l'ID de la ville on peut parser ainsi :

``` javascript
var scrapMeteo = function(body, date){
  var results = JSON.parse(body);
  var previsions = results.result.previsions;
  tts = "Prévision météo pour ";
  moment = "";
  if (previsions["0_matin"]) { moment="0_matin"; tts+="ce matin. "; }
  else if (previsions["0_midi"]) { moment="0_midi"; tts+="ce midi. "; }
  else if (previsions["0_soir"]) { moment="0_soir"; tts+="ce soir. "; }
  else if (previsions["0_nuit"]) { moment="0_nuit"; tts+="cette nuit. "; }

  tts += previsions[moment]["description"]+". Température entre "+ previsions[moment]["temperatureMax"]+" degrés et "+previsions[moment]["temperatureMin"]+" degrés et un vent à "+previsions[moment]["vitesseVent"]+" kilomètres par heure."
  return tts;
}
```

**Comment by JpEncausse** [comment]
J'ai corrigé pour tenir compte de la nouvel URL et du JSON

**Comment by Aymkdn** [comment]
Merci :+1:
